import { Pill } from '../Pill'
import { Chip } from '../Chip'
import { Button } from '../Button'
import { ProvChip } from '../ProvChip'
import type { EnrichStatus } from './EnrichCell'
import type { ProviderRef } from './Waterfall'
import styles from './provenance.module.css'

/** Show just the host of a source URL in the citation list. */
function sourceHost(url: string): string {
  const m = /^[a-z]+:\/\/([^/]+)/i.exec(url)
  return m?.[1] ?? url
}

const STATUS_LABEL: Record<EnrichStatus, string> = {
  queued: 'Queued',
  running: 'Running',
  success: 'Success',
  empty: 'Empty',
  failed: 'Failed',
  cached: 'Cached',
}

/** One structured-output field row in the provenance breakdown (Phase 3, US-3.2). */
export interface ProvenanceField {
  label: string
  /** Coerced value written to the field's column (omit for an Empty field). */
  value?: string
  status: EnrichStatus
  /** Reason an Empty field could not be produced. */
  reason?: string
}

export interface ProvenanceCardProps {
  status: EnrichStatus
  /** The resolved value written to the cell. */
  value?: string
  provider?: ProviderRef
  /** e.g. "step 2 of 3". */
  step?: string
  operation?: string
  /** Pre-formatted timestamp, e.g. "2m ago". */
  at?: string
  /** Credits, e.g. "1 cr". */
  cost?: string
  /** Dollar cost — Admin only; omit to hide. */
  costUsd?: string
  fromCache?: boolean
  /** 0..1. */
  confidence?: number
  /** Failure reason / acceptance note. */
  reason?: string
  /** Retry action (typically for Failed cells). */
  onRetry?: () => void
  // ---- AI extensions (Phase 3) — all optional, backward compatible ----
  /** Model label, e.g. "Claude Haiku 4.5" (rendered as a cobalt chip). */
  model?: string
  /** The resolved prompt for this row (clamped), for explainability. */
  promptSnippet?: string
  /** Structured-output field breakdown (US-3.2). */
  fields?: ProvenanceField[]
  /** Web-research agent source citations (US-3.4). */
  sources?: { url: string; title?: string }[]
}

// The content of the per-cell provenance popover: which provider/step supplied
// the value, when, at what cost (or "from cache"), and — for failures — the
// reason plus a retry affordance.
export function ProvenanceCard({ status, value, provider, step, operation, at, cost, costUsd, fromCache, confidence, reason, onRetry, model, promptSnippet, fields, sources }: ProvenanceCardProps) {
  return (
    <div className={styles.card}>
      <div className={styles.head}>
        <Pill status={status}>{STATUS_LABEL[status]}</Pill>
        {at ? <span className={styles.meta}>{at}</span> : null}
      </div>

      {value ? <div className={styles.value}>{value}</div> : null}

      {model ? (
        <div className={styles.row}>
          generated by
          <Chip tone="cobalt">{model}</Chip>
          {operation ? <span className={styles.meta}>· {operation}</span> : null}
        </div>
      ) : provider ? (
        <div className={styles.row}>
          supplied by
          <ProvChip mono={provider.glyph} bg={provider.color} color={provider.inkColor}>
            {provider.name}
          </ProvChip>
          {operation ? <span className={styles.meta}>· {operation}</span> : null}
        </div>
      ) : null}

      {promptSnippet ? <div className={styles.snippet}>{promptSnippet}</div> : null}

      {fields && fields.length > 0 ? (
        <div className={styles.fields}>
          {fields.map((f) => (
            <div key={f.label} className={styles.fieldRow}>
              <i className={styles.fieldDot} style={{ background: `var(--st-${f.status})` }} />
              <span className={styles.fieldLabel}>{f.label}</span>
              {f.status === 'empty' || f.value == null ? (
                <span className={styles.fieldEmpty}>{f.reason ?? 'empty'}</span>
              ) : (
                <span className={styles.fieldValue}>{f.value}</span>
              )}
            </div>
          ))}
        </div>
      ) : null}

      {sources && sources.length > 0 ? (
        <div className={styles.sources}>
          <span className={styles.meta}>sources · {sources.length}</span>
          {sources.map((s, i) => (
            <a key={`${s.url}-${i}`} className={styles.sourceRow} href={s.url} target="_blank" rel="noreferrer">
              {s.title ? `${s.title} — ` : ''}
              {sourceHost(s.url)}
            </a>
          ))}
        </div>
      ) : null}

      {step ? <span className={styles.meta}>{step}</span> : null}

      {confidence != null ? (
        <div className={styles.conf}>
          <span className={styles.meta}>confidence · {Math.round(confidence * 100)}%</span>
          <span className={styles.confTrack}>
            <i style={{ width: `${Math.round(confidence * 100)}%` }} />
          </span>
        </div>
      ) : null}

      <div className={styles.row}>
        {fromCache ? (
          <Chip tone="cached">from cache</Chip>
        ) : cost ? (
          <>
            <span className={styles.cost}>{cost}</span>
            {costUsd ? <span className={styles.meta}>· {costUsd}</span> : null}
          </>
        ) : (
          <span className={styles.meta}>no charge</span>
        )}
      </div>

      {reason ? <div className={styles.reason}>{reason}</div> : null}

      {onRetry ? (
        <>
          <div className={styles.divider} />
          <Button variant="ghost" size="sm" onClick={onRetry}>
            Retry this cell
          </Button>
        </>
      ) : null}
    </div>
  )
}
